export const ADDAUTHENTICATEUSER = "ADDAUTHENTICATEUSER";
export const UPDATEACTIONSTATUS = "UPDATEACTIONSTATUS";
export const TOGGLEMODALAUTH = "TOGGLEMODALAUTH";
export const PASS_TO_NEXT_POPULAR_PAGE = "PASS_TO_NEXT_POPULAR_PAGE";